{\rtf1\ansi\ansicpg936\cocoartf1671\cocoasubrtf200
{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset134 PingFangSC-Regular;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 spring:\
    profiles:\
      active:\
      - dev\
\
---\
spring:\
    profiles: dev    #
\f1 \'bf\'aa\'b7\'a2\'bb\'b7\'be\'b3
\f0 \
    application:\
         name
\f1 \'a3\'ba
\f0  microservicecloud-config-liujun-dev\
---\
spring:\
    profiles: test   #
\f1 \'b2\'e2\'ca\'d4\'bb\'b7\'be\'b3
\f0 \
    application:\
         name
\f1 \'a3\'ba
\f0  microservicecloud-config-liujun-test\
\
}